[build-system]
requires = ["flit_core >=3.2,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "dogsHelp"
authors = [{name = "Valeev Gleb", email = "valeev_101@bk.ru"}]
dynamic = ["version", "description"]
